//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BucBoard.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfficeHour
    {
        public int officeHoursID { get; set; }
        public Nullable<int> startingHours { get; set; }
        public Nullable<int> startingMinutes { get; set; }
        public Nullable<int> endingHours { get; set; }
        public Nullable<int> endingMinutes { get; set; }
        public string day { get; set; }
        public int userID { get; set; }
    
        public virtual User User { get; set; }
    }
}
